# Generated by Django 2.2.4 on 2020-04-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationgolfofomaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='timeslot',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
